name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.2.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a24b3dc5f53c0229eb7c2e4905bb3583e137db3ac29125867feb284fe7dc9570"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "/resources/datapack/required/"
