name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf1fd7a780d73b7e8e0940157b1d155c1b1e3ef3acaaf3f05ffb3cde1e63cc0c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
unsup = "1.2.0"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "/resources/datapack/required/"
