name = "Maddy Origins SMP Redux"
author = "Maddy"
version = "0.3.23"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f220dd4725659e2731d09cd079dd7c7ed41a5183fcf1895dfb87ac7f692718d7"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
unsup = "1.2.0"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "/resources/datapack/required/"
