enabled = true
sendServerConfig = true
sendDistance = true
maxDistance = 2048
directionPrecision = 300.0
ticksBetweenUpdates = 5
sneakingHides = true
pumpkinHides = true
mobHeadsHide = true
invisibilityHides = true
visible = true
visibleEmpty = false
acceptServerConfig = false
fadeMarkers = true
fadeStart = 128
fadeEnd = 2048
fadeEndOpacity = 0.30000001192092896
showHeight = true
alwaysShowHeads = false
showHeadsOnTab = true
showNamesOnTab = true
colorMode = "CUSTOM"
constantColor = 0xffffff